// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtwvtzslwkhungnrjtdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0d3Z0enNsd2todW5nbnJqdGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjA0ODEsImV4cCI6MjA3MDMzNjQ4MX0.e8nLaSTvhp7-X6zx-aCU4ZT_pERrUTRjVQ4AorH3t8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});